<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-05T17:30:33Z" name="Default suite" finished-at="2025-05-05T17:30:38Z" duration-ms="4732">
    <groups>
    </groups>
    <test started-at="2025-05-05T17:30:33Z" name="Default test" finished-at="2025-05-05T17:30:38Z" duration-ms="4732">
      <class name="com.example.myproject.AppTest">
        <test-method is-config="true" signature="startApp()[pri:0, instance:com.example.myproject.AppTest@2f67a4d3]" started-at="2025-05-05T17:30:34Z" name="startApp" finished-at="2025-05-05T17:30:35Z" duration-ms="1964" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startApp -->
        <test-method signature="loginTest()[pri:0, instance:com.example.myproject.AppTest@2f67a4d3]" started-at="2025-05-05T17:30:35Z" name="loginTest" finished-at="2025-05-05T17:30:38Z" duration-ms="2299" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Correct expected [Become Seller] but found [Become a Seller]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Correct expected [Become Seller] but found [Become a Seller]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.example.myproject.AppTest.loginTest(AppTest.java:29)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:com.example.myproject.AppTest@2f67a4d3]" started-at="2025-05-05T17:30:38Z" name="closeApp" finished-at="2025-05-05T17:30:38Z" duration-ms="436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.example.myproject.AppTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
